# Generated by Django 2.2.5 on 2019-09-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redapp', '0002_auto_20190923_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='phone',
        ),
    ]
